# rouser changelog generation — https://git-cliff.org/

[changelog]
trim = true
post_bumps = 1

body = """
{% if version %}
    ## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*{{ commit.scope }}*: {% endif %}{{ commit.message | trim | upper_first }}{% if commit.github.contributor %} — [@{{ commit.github.username }}](https://github.com/{{ commit.github.username }}){% endif %}
    {% endfor %}
{% endfor %}
"""

[git]
conventional_commits = true
filter_unconventional = false
split_prerelease = true
sort_commits = "newest"

commit_preprocessors = [
    { pattern = '\(#(\d+)\)', replace = '[#$1](https://github.com/owaindjones/rouser/issues/$1)' },
]

commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->Features" },
    { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
    { message = "^perf", group = "<!-- 2 -->Performance Improvements" },
    { message = "^revert", group = "<!-- 3 -->Reverts" },
    { message = "^.*!:", group = "<!-- 4 -->Breaking Changes" },
    { footer = "BREAKING CHANGE", group = "<!-- 4 -->Breaking Changes" },
    { message = "^docs", group = "<!-- 5 -->Documentation", skip = true },
    { message = "^test", group = "<!-- 6 -->Testing", skip = true },
    { message = "^refactor", group = "<!-- 7 -->Code Refactoring", skip = true },
    { message = "^chore", group = "<!-- 8 -->Chores", skip = true },
    { message = "^ci", group = "<!-- 9 -->CI", skip = true },
    { message = ".", default = true, skip = false },
]
